name: Code Analysis
on:
  push:
    branches: [ ci-cd-task ]
  pull_request:
    branches: [ ci-cd-task ]
jobs:
  analyze_application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Install packages
        run: |
          npm ci

      - name: Eslint and Prettier checks
        run: |
          npm run lint:check
          npm run format:check

  build-docker-image:
    needs: analyze_application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build docker image
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-task:latest
          outputs: type=docker,dest=/tmp/docker-task.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-task
          path: /tmp/docker-task.tar

  push-docker-image:
    needs: build-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-task
          path: /tmp

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Load Docker image
        run: |
          docker load --input /tmp/docker-task.tar

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/docker-task

  run-docker-image:
    needs: push-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker image
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/docker-task:latest

      - name: Create Docker Network
        run: docker network create connect

      - name: Run Docker image
        run: |
          docker run --network connect --name myimage -p 80:80 -d ${{ secrets.DOCKERHUB_USERNAME }}/docker-task

      - name: curl
        run: docker run --rm --network connect curlimages/curl:latest http://myimage/
